# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  sign-packages: opennms/sign-packages@2.3.0
executors:
  caweb-executor:
    docker:
      - image: php:7.4-alpine

workflows:
  verify_standards:
    jobs:
      - build_env
      - standard:
          requires:
            - build_env
          filters:
            branches:
              ignore:
                - gh-page

working_directory: ~/repo

jobs:
  autodoc:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run: git config --global user.name "guzmanjd86@gmail.com"
      - run: git config --global user.email "Danny Guzman"
      - run: composer i --no-dev
      - run: wget -O phpDoc.phar https://phpdoc.org/phpDocumentor.phar
      - run: chmod +x phpDoc.phar
      - run: ./phpDoc.phar . --force
      - run: git checkout gh-pages
      - run: rm -rf *
      - run: mv .docs/* .
      - run: rm -rf .docs/
      - run: git add .
      - run: git commit -m "Autogenerated docs via CircleCi"
      - run: git push origin gh-pages
      - run: git remote add admin https://github.com/Danny-Guzman/CAWeb
      - run: git fetch admin
      - run: git pull admin gh-pages --no-commit -X theirs
      - run: git reset --hard admin/gh-pages
      - run: git pull origin gh-pages --no-commit -X ours 
      - run: git add .
      - run: git push admin gh-pages 
      - run: git remote add cawebpublishing https://github.com/CAWebPublishing/CAWeb
      - run: git fetch cawebpublishing
      - run: git pull cawebpublishing gh-pages --no-commit -X theirs
      - run: git reset --hard cawebpublishing/gh-pages
      - run: git pull origin gh-pages --no-commit -X ours 
      - run: git add .
      - run: git push cawebpublishing gh-pages 
  build_env:
    executor: caweb-executor
    steps:
        - run: apk add git
        - run: 
            name: "Install Composer"
            command: 
              php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
              php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
              php composer-setup.php
              php -r "unlink('composer-setup.php');"
        - persist_to_workspace:
            root: /
            paths: 
              - /tmp
  standard:
    executor: caweb-executor
    steps:
      - attach_workspace:
          at: /
      - checkout
      - run: composer update
      - run: 
          command: |
            declare -a files=( 
              'divi/'
              'page-templates/'
              'inc/'
              '404.php' 
              'archive.php' 
              'author.php' 
              'category.php' 
              'date.php' 
              'footer.php' 
              'functions.php' 
              'header.php'
              'index.php'
              'page.php'
              'single.php'
              'tag.php'
              )
            for f in ${files[@]}; do
                if [ -n "$( ./vendor/bin/phpcs $f )" ]; then
                  echo "$( ./vendor/bin/phpcs $f )"
                  exit 1
                fi
            done


              