# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  sign-packages: opennms/sign-packages@2.3.0
executors:
  caweb-executor:
    docker:
      - image: circleci/php:7.4
    working_directory: /tmp

workflows:
  verify_standards:
    jobs:
      - build_env
      - standard:
          requires:
            - build_env
          filters:
            branches:
              ignore:
                - gh-page

working_directory: ~/repo

jobs:
  autodoc:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run: git config --global user.name "guzmanjd86@gmail.com"
      - run: git config --global user.email "Danny Guzman"
      - run: composer i --no-dev
      - run: wget -O phpDoc.phar https://phpdoc.org/phpDocumentor.phar
      - run: chmod +x phpDoc.phar
      - run: ./phpDoc.phar . --force
      - run: git checkout gh-pages
      - run: rm -rf *
      - run: mv .docs/* .
      - run: rm -rf .docs/
      - run: git add .
      - run: git commit -m "Autogenerated docs via CircleCi"
      - run: git push origin gh-pages
      - run: git remote add admin https://github.com/Danny-Guzman/CAWeb
      - run: git fetch admin
      - run: git pull admin gh-pages --no-commit -X theirs
      - run: git reset --hard admin/gh-pages
      - run: git pull origin gh-pages --no-commit -X ours 
      - run: git add .
      - run: git push admin gh-pages 
      - run: git remote add cawebpublishing https://github.com/CAWebPublishing/CAWeb
      - run: git fetch cawebpublishing
      - run: git pull cawebpublishing gh-pages --no-commit -X theirs
      - run: git reset --hard cawebpublishing/gh-pages
      - run: git pull origin gh-pages --no-commit -X ours 
      - run: git add .
      - run: git push cawebpublishing gh-pages 


  standard:
      docker:
        - image: circleci/php:7.4
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - run: 
            name: "Set GPG_SECRET_KEY"
            command: |
              export GPG_SECRET_KEY=$( echo -e "$GPG_KEYS" | base64 )
        - sign-packages/install-deb-dependencies:
            use_sudo: true
        - sign-packages/setup-env
        - sign-packages/sign-debs:
            gnupg_key: opennms@opennms.org
            packages: '*.deb'
            type: maint
          - checkout
          - run: composer update
          - run: 
              command: |
                declare -a files=( 
                  'divi/'
                  'page-templates/'
                  'inc/'
                  '404.php' 
                  'archive.php' 
                  'author.php' 
                  'category.php' 
                  'date.php' 
                  'footer.php' 
                  'functions.php' 
                  'header.php'
                  'index.php'
                  'page.php'
                  'single.php'
                  'tag.php'
                  )
                for f in ${files[@]}; do
                    if [ -n "$( ./vendor/bin/phpcs $f )" ]; then
                      echo "$( ./vendor/bin/phpcs $f )"
                      exit 1
                    fi
                done