#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
#exec git diff-index --check --cached $against --

# if composer is not installed 
if [ -z "$(composer)" ]; then
	exec echo "composer is used to enforce WordPress Theme Coding Standards. If you do not want to run the check, run git commit --no-verify"

# composer is installed
else
	# install packages
	composer i

	# Run PHP Code Beautifier and Fixer
	echo "Running PHP Code Beautifer and Fixer. This may take up to several minutes..."
	./vendor/bin/phpcbf .

	# Run PHP CS Fixer
	echo "Running PHP CS Fixer. This may take up to several minutes..."
	./vendor/bin/php-cs-fixer fix . --config .circleci/caweb.php_cs
	
	# run PHP_CodeSniffer
	echo "Running PHP CodeSniffer. This may take up to several minutes..."
  
	output=$(./vendor/bin/phpcs .)

	if [ "$output"  ]; then
		echo "$output"
		exit 1
	fi
fi


exit 0
