blank_issues_enabled: true
contact_links:
  - name: CAWebPublishing Support
    url: https://github.com/CA-CODE-Works/CAWeb/issues/new?template=bug-form.yml&labels=bug&assignees=Danny-Guzman
    about: Please submit CAWeb related issues here.
