#!/usr/bin/env node

/**
 * External dependencies
 */
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
import { optimize, loadConfig } from 'svgo';
import { parseSync } from 'svgson';

// Constants
const require = createRequire( import.meta.url );
const nameSpace = 'caweb';
const libPath = path.join(process.cwd(), 'lib');

const srcPath = path.join(process.cwd(), 'src');
const iconsPath = path.join(srcPath, 'icons');

// SVGO Config
const svgoConfig = await loadConfig( path.join( libPath, 'configs', 'svgo.config.js' ) );

// Main SVG file
const fontsDir = path.resolve( require.resolve('@caweb/icon-library'), '..', 'fonts');
const mainSVGFile = fs.readdirSync( fontsDir, { recursive: true } ).filter( (e) => e.endsWith( '.svg' ) )[0];
const mstrSVGContent = fs.readFileSync(path.join( fontsDir, mainSVGFile )).toString();
const mstrSVG = parseSync( optimize( mstrSVGContent, svgoConfig ).data );

// Base jsx template file
const baseJSX = fs.readFileSync( path.join( libPath, 'templates', 'base.tsx.template' ) ).toString();

// master svg definition list
const mstrFontDefs = mstrSVG.children.filter( e => 'defs' === e.name )[0].children[0].children;
const mstrFontList = mstrFontDefs.filter(e => 'glyph' === e.name);

// we use this value for the svg viewBox attribute
const unitsPerEM = mstrFontDefs.filter( e => 'font-face' === e.name )[0].attributes['units-per-em'];
const descent = mstrFontDefs.filter( e => 'font-face' === e.name )[0].attributes['descent'];
const viewBox = `0 ${descent} ${unitsPerEM} ${unitsPerEM}`;

// we clear the icons folder before writing new files
// this will eliminate any old files that are not in the new set of icons
fs.rmSync( iconsPath, { recursive: true, force: true } );

// icon index file content
let indexContent = [`// Autogenerated file, do not edit directly\n`];

// used for module logo in the module library
let moduleLogo = 'module-logo';
let moduleDir = path.join( iconsPath, moduleLogo );
let moduleJson = {};
let moduleDimensions = 'M 0.222656 15.34375 C 0.183594 15.328125 0.121094 15.25 0.078125 15.171875 C 0.0117188 15.050781 0 14.683594 0 12.976562 L 0 10.925781 L 0.304688 10.628906 L 3.15625 10.628906 L 3.171875 11.441406 C 3.1875 12.175781 3.199219 12.269531 3.296875 12.402344 C 3.539062 12.710938 3.671875 12.75 4.730469 12.765625 L 5.691406 12.785156 L 5.691406 15.0625 L 5.417969 15.378906 L 2.855469 15.371094 C 1.445312 15.371094 0.257812 15.359375 0.222656 15.34375 Z M 7.742188 14.820312 L 7.585938 14.671875 L 7.585938 12.773438 L 10.238281 12.773438 C 12.882812 12.773438 12.886719 12.773438 13.121094 12.660156 C 13.527344 12.457031 13.5625 12.339844 13.582031 11.207031 L 13.605469 10.222656 L 16.550781 10.222656 L 16.675781 10.347656 L 16.808594 10.472656 L 16.808594 14.703125 L 16.480469 14.96875 L 7.894531 14.96875 Z M 0.574219 8.863281 L 0.449219 8.730469 L 0.433594 5.304688 C 0.421875 3.414062 0.433594 1.769531 0.449219 1.648438 C 0.46875 1.515625 0.53125 1.378906 0.605469 1.304688 L 0.730469 1.183594 L 3.242188 1.183594 C 5.8125 1.183594 5.890625 1.1875 6.042969 1.382812 C 6.089844 1.445312 6.105469 1.816406 6.113281 2.730469 L 6.113281 3.992188 L 5.046875 3.992188 C 3.921875 3.992188 3.636719 4.03125 3.433594 4.210938 C 3.160156 4.457031 3.160156 4.441406 3.160156 6.800781 L 3.160156 8.996094 L 0.699219 8.996094 Z M 13.59375 6.664062 C 13.59375 5.507812 13.574219 4.757812 13.535156 4.628906 C 13.460938 4.375 13.203125 4.109375 12.960938 4.042969 C 12.855469 4.011719 11.824219 3.992188 10.476562 3.992188 L 8.167969 3.992188 L 8.167969 2.601562 C 8.167969 1.046875 8.183594 0.964844 8.53125 0.738281 L 8.710938 0.621094 L 12.816406 0.621094 C 17.367188 0.621094 17.175781 0.605469 17.394531 0.949219 C 17.488281 1.101562 17.492188 1.269531 17.492188 4.5625 L 17.492188 8.019531 L 17.328125 8.199219 C 17.242188 8.300781 17.082031 8.402344 16.976562 8.433594 C 16.867188 8.464844 16.109375 8.484375 15.191406 8.484375 L 13.59375 8.484375 Z M 5.691406 10.425781 L 10.960938 10.425781 L 10.960938 6.289062 L 5.691406 6.289062 Z M 10.960938 5.625 L 5.691406 5.625 C 5.3125 5.625 5.003906 5.921875 5.003906 6.289062 L 5.003906 10.425781 C 5.003906 10.792969 5.3125 11.089844 5.691406 11.089844 L 10.960938 11.089844 C 11.339844 11.089844 11.644531 10.792969 11.644531 10.425781 L 11.644531 6.289062 C 11.644531 5.921875 11.339844 5.625 10.960938 5.625 Z M 6.375 6.953125 L 10.273438 6.953125 L 10.273438 9.761719 L 6.375 9.761719 Z M 6.375 6.953125';

// Add any integrations here
import { iconImports, outputIntegrationFile } from './icon.ts';

// save all the icons
let allIcons = [];

// loop through the SVG file list and create a new file for each icon
mstrFontList.forEach( (glyph) => { 
     // glyph attributes
     let { 
          'glyph-name': name, 
          'data-tags': tags, 
          'd' : dimensions,
          'unicode': decodedUnicode
     } = glyph.attributes;

     // if the name is not defined we skip it
     if( ! name ){
          return;
     }

     // glyph json data
     let glyphJson = {
          decodedUnicode,
          fontWeight: parseInt( 400 ),
     }

     // We get the encoded unicode value from the master svg content file, otherwise the glyph renders the icon not the unicode value
     let matches = mstrSVGContent.match( new RegExp( `unicode="(.*)" glyph-name="${name}"` ) );

     // if there is a match we can continue
     if( matches ){
          // remove the name from the tags.
          tags = tags ? tags.replace( name, '' ).split( ',' ).filter(Boolean) : '';

          let titleName = name.replaceAll('_', ' ').toLowerCase().split(' ').map( ( w ) => w.charAt(0).toUpperCase() + w.slice(1) ).join(' ');

          // complete the glyph json data
          glyphJson.name = titleName;
          glyphJson.unicode = matches[1];
          glyphJson.styles = [ 'caweb' ];
          glyphJson.searchTerms = [nameSpace, name, titleName.toLowerCase(), tags].join(' ').trim();

          // the module logo is the caweb icon
          if( name === 'caweb' ){
               
               moduleJson = glyphJson;
               moduleJson.name = 'module-logo';
          }

          let iconDir = path.join( iconsPath, name );
          
          // create the output directory if it doesn't exist
          if (  ! fs.existsSync( iconDir ) ) {
               fs.mkdirSync( iconDir, { recursive: true } );
          }
          
          // output the icon tsx file
          fs.writeFileSync( 
               path.join( iconDir, `${name}.tsx`), 
               baseJSX
                    .replaceAll( '{nameSpace}', nameSpace )
                    .replaceAll( '{name}', name )
                    .replaceAll( '{viewBox}', viewBox )
                    .replaceAll( '{dimensions}', dimensions )
          );

          // output the icon json file
          fs.writeFileSync( 
               path.join( iconDir, `${name}.json`), 
               JSON.stringify( glyphJson, null, 4 ) 
          );

          // add to the all icons list
          allIcons.push( glyphJson );

          // add the import to the index file
          let exportName = name.replaceAll(/[-_]([\w]{1})/g, (m, g) => g.toUpperCase());
          indexContent.push( `export * as ${exportName} from './${name}/${name}';\n` );
          iconImports.push( exportName );
     }else{
          console.log( `Icon ${name} not found in master SVG file` );
          console.log( 'Glyph Data:', glyph );
     }
});

// generate the module library logo
if( ! fs.existsSync( moduleDir ) ){
     fs.mkdirSync( moduleDir, { recursive: true } );
}

// output the module logo json file
fs.writeFileSync( 
     path.join( moduleDir, `${moduleLogo}.json`), 
     JSON.stringify( moduleJson, null, 4 ) 
);

// output the module logo tsx file
fs.writeFileSync( 
     path.join( moduleDir, `${moduleLogo}.tsx`), 
     baseJSX
          .replaceAll( '{nameSpace}', nameSpace )
          .replaceAll( '{name}', moduleLogo )
          .replaceAll( '{viewBox}', '0 0 16 16' )
          .replaceAll( '{dimensions}', moduleDimensions )
);

// add module logo export to index file
indexContent.push( `export * as moduleLogo from './${moduleLogo}/${moduleLogo}';\n` );

// add module logo to icon imports
iconImports.push( 'moduleLogo' );

// write the index.ts file
fs.writeFileSync(
     path.join( iconsPath, 'index.ts' ),
     indexContent.join( '' )
);

// write the full icon list json file
fs.writeFileSync(
     path.join( iconsPath, 'iconList.json' ),
     JSON.stringify( allIcons, null, 4 )
);

// write the divi.ts integration file
fs.writeFileSync(
     path.join( srcPath, 'icons.ts' ),
     outputIntegrationFile()
 );